name: Store data in Drive
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Archive files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -r archive.zip *

      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: secrets.UPLOAD_TO_DRIVE
          filename: "_id_pass.png"
          folderId: 1fHO-KzY0mMIsCrQgM0gkp8tyeGaQdlUw
          name: "_id_pass.png" # optional string
          overwrite: "true" # optional boolean
