name: upload to Drive
on:
  push:
    branches:
      - 'master'
      - 'main'
      - '!test'

jobs:
  gdrive-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload vn_chart.csv
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: datasets/vn_chart.csv
          name: vn_chart.csv
          folderId: ${{ secrets.FOLDERID }}
          credentials: ${{ secrets.CREDENTIALS }}
          encoded: true
          overwrite: true

      - name: Upload global_chart.csv
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: datasets/global_chart.csv
          name: global_chart.csv
          folderId: ${{ secrets.FOLDERID }}
          credentials: ${{ secrets.CREDENTIALS }}
          encoded: true
          overwrite: true

      - name: Upload audio_features.csv
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: datasets/audio_features.csv
          name: audio_features.csv
          folderId: ${{ secrets.FOLDERID }}
          credentials: ${{ secrets.CREDENTIALS }}
          encoded: true
          overwrite: true


      - name: Upload audio_features.csv
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: datasets/audio_features_no_in.csv
          name: audio_features_no_in.csv
          folderId: ${{ secrets.FOLDERID }}
          credentials: ${{ secrets.CREDENTIALS }}
          encoded: true
          overwrite: true
