name: upload to Drive
on:
  push:
    branches:
      - 'master'
      - 'main'
      - '!test'

jobs:
  gdrive-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to gdrive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: datasets/vn_chart.csv
          name: vn_chart.csv
          folderId: ${{ secrets.FOLDERID }}
          credentials: ${{ secrets.CREDENTIALS }}
          encoded: true
          overwrite: true
