name: Store data in Drive
on:
  schedule:
    - cron: '*/5 * * * *'# 4 PM UTC     
jobs:
  buildAndTestForSomePlatforms:
    name: Upload readme to drive
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
      # Upload to Drive
      - name: Upload vn_chart.csv to Google Drive
        uses: tungbtt/Spotify_Song_Trend_Insights/@master
        with:
          target: datasets/vn_chart.csv
          credentials: secrets.UPLOAD_TO_DRIVE
          folder: 1fHO-KzY0mMIsCrQgM0gkp8tyeGaQdlUw
